## Procesado de datos financieros de alta frecuencia para ML

Este notebook implementa un pipeline de preprocesado de datos financieros de alta frecuencia para BTC/USDT (datos de 1 minuto) siguiendo un enfoque inspirado en Marcos López de Prado. El objetivo es transformar datos brutos en una estructura adecuada para modelos de machine learning, respetando la naturaleza temporal y el ruido propio de los mercados financieros.

**Resumen de las etapas del pipeline:**
- **Sección 0**: Setup, parámetros globales y carga inicial de datos.
- **Sección 1**: Construcción y comparación de barras alternativas (tick, volumen, dólar) y selección de dollar bars.
- **Sección 2**: Diferenciación fraccional de la serie de precios y elección del grado de diferenciación.
- **Sección 3**: Construcción de features internas y limpieza de la matriz de covarianza mediante eigenvalue clipping.
- **Sección 4**: Etiquetado de eventos con el método de triple barrera (thresholds fijos y dinámicos).
- **Sección 5**: Definición de esquemas de validación cruzada temporal (70/30, 80/20, 90/10).

## 0. Setup global del entorno

En esta sección se importan las librerías básicas y se fijan los parámetros globales del análisis.

In [13]:
# Imports básicos del proyecto
import os
import glob

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# Configuración de estilo básica para las figuras de matplotlib
plt.style.use("default")  # Fondo blanco por defecto

# ======================================================================
# ### PARÁMETROS ###
# ----------------------------------------------------------------------
# Rango temporal de análisis (el usuario solo debería modificar estas dos
# variables para cambiar el periodo de trabajo del notebook).
# ======================================================================
DATE_START = "2026-02-01"
DATE_END   = "2026-02-28"

print("Rango temporal configurado:")
print(f"  Fecha inicio: {DATE_START}")
print(f"  Fecha fin   : {DATE_END}")

Rango temporal configurado:
  Fecha inicio: 2026-02-01
  Fecha fin   : 2026-02-28

### 0.1. Descarga y localización del archivo de datos

En esta sección se descarga el dataset histórico de BTC/USDT desde Kaggle mediante `kagglehub` y se localiza de forma automática el archivo CSV correcto dentro de la carpeta descargada.

In [14]:
# Descarga del dataset de Kaggle y localización del archivo CSV principal

# Código de descarga fijado por el enunciado (no modificar)
import kagglehub
path = kagglehub.dataset_download("mczielinski/bitcoin-historical-data")
print("Path to dataset files:", path)

# Búsqueda recursiva de todos los archivos CSV dentro del path descargado
csv_pattern = os.path.join(path, "**", "*.csv")
csv_files = glob.glob(csv_pattern, recursive=True)

if not csv_files:
    raise FileNotFoundError("No se encontraron archivos CSV en la ruta descargada de Kaggle.")

print("\nArchivos CSV encontrados:")
for f in csv_files:
    print("  -", f)

# Estrategia de selección del archivo principal:
# 1) Preferir archivos cuyo nombre contenga referencias a BTCUSD/BTCUSDT.
# 2) Si no se encuentra ninguno, seleccionar el CSV de mayor tamaño (en bytes).

preferred_keywords = ["btcusd", "btcusdt", "btc_usd", "btc-usd"]

candidates_preferred = []
for f in csv_files:
    name_lower = os.path.basename(f).lower()
    if any(kw in name_lower for kw in preferred_keywords):
        candidates_preferred.append(f)

if candidates_preferred:
    # Si hay varios candidatos preferidos, elegir el más grande por tamaño
    csv_path = max(candidates_preferred, key=lambda p: os.path.getsize(p))
    strategy = "archivo con nombre que coincide con BTCUSD/BTCUSDT"
else:
    # Si no hay coincidencias en el nombre, elegir el CSV más grande en general
    csv_path = max(csv_files, key=lambda p: os.path.getsize(p))
    strategy = "archivo CSV de mayor tamaño (fallback)"

print("\nArchivo CSV seleccionado (", strategy, "):", sep="")
print("  ", csv_path)

# Guardamos la ruta seleccionada en una variable global para reutilizarla después
DATA_CSV_PATH = csv_path

Path to dataset files: C:\Users\Usuario\.cache\kagglehub\datasets\mczielinski\bitcoin-historical-data\versions\538

Archivos CSV encontrados:
  - C:\Users\Usuario\.cache\kagglehub\datasets\mczielinski\bitcoin-historical-data\versions\538\btcusd_1-min_data.csv

Archivo CSV seleccionado (archivo con nombre que coincide con BTCUSD/BTCUSDT):
   C:\Users\Usuario\.cache\kagglehub\datasets\mczielinski\bitcoin-historical-data\versions\538\btcusd_1-min_data.csv

### 0.2. Carga del CSV e inspección inicial del dataset

En esta sección se carga el archivo CSV seleccionado en un `DataFrame` de `pandas` y se realiza una inspección inicial básica (forma, tipos de datos, primeras y últimas filas). También se detecta de forma robusta cuál es la columna temporal y se comprueba si los datos están ordenados de forma cronológica o inversa.

In [16]:
# Carga del CSV seleccionado y exploración básica

# Leemos el archivo CSV seleccionado en la celda anterior
print("Leyendo CSV desde:")
print("  ", DATA_CSV_PATH)

df_raw = pd.read_csv(DATA_CSV_PATH)

print("\nDimensiones del DataFrame bruto:")
print("  shape =", df_raw.shape)

print("\nTipos de datos (dtypes):")
print(df_raw.dtypes)

print("\nPrimeras 3 filas:")
display(df_raw.head(3))

print("\nÚltimas 3 filas:")
display(df_raw.tail(3))

print("\nResumen df.info():")
df_raw.info()

# ----------------------------------------------------------------------
# Detección robusta de la columna temporal
# ----------------------------------------------------------------------

possible_time_names = [
    "timestamp", "date", "time", "datetime", "open time", "open_time"
]

# Buscamos coincidencias case-insensitive y permitimos espacios/guiones bajos
lower_cols = {col.lower(): col for col in df_raw.columns}

found_time_col = None
for candidate in possible_time_names:
    for col_lower, col_original in lower_cols.items():
        if candidate in col_lower:
            found_time_col = col_original
            break
    if found_time_col is not None:
        break

if found_time_col is None:
    raise ValueError(
        "No se pudo detectar una columna temporal. Revise los nombres de columna "
        "y actualice la lista de posibles variantes."
    )

print("\nColumna temporal detectada:")
print("  ", found_time_col)

# ----------------------------------------------------------------------
# Detección de si el orden temporal está invertido
# ----------------------------------------------------------------------

# Tomamos algunas muestras del principio y del final para intentar inferir el orden
sample_start = df_raw[found_time_col].head(5)
sample_end = df_raw[found_time_col].tail(5)

# Intentamos convertir estas muestras a datetime de forma flexible
sample_start_dt = pd.to_datetime(sample_start, errors="coerce")
sample_end_dt = pd.to_datetime(sample_end, errors="coerce")

is_reverse_order = False
if not sample_start_dt.isna().all() and not sample_end_dt.isna().all():
    first_ts = sample_start_dt.iloc[0]
    last_ts = sample_end_dt.iloc[-1]
    if pd.notna(first_ts) and pd.notna(last_ts):
        is_reverse_order = first_ts > last_ts

if is_reverse_order:
    print("\nOrden temporal detectado: INVERSO (últimas fechas primero). Se corregirá en la etapa de limpieza temporal.")
else:
    print("\nOrden temporal detectado: CRONOLÓGICO o no claramente inverso (se confirmará tras la conversión a datetime).")

# Guardamos el nombre de la columna temporal para usarlo en la siguiente fase
time_column_name = found_time_col

Leyendo CSV desde:
   C:\Users\Usuario\.cache\kagglehub\datasets\mczielinski\bitcoin-historical-data\versions\538\btcusd_1-min_data.csv

Dimensiones del DataFrame bruto:
  shape = (7467523, 6)

Tipos de datos (dtypes):
Timestamp    float64
Open         float64
High         float64
Low          float64
Close        float64
Volume       float64
dtype: object

Primeras 3 filas:

      Timestamp  Open  High   Low  Close  Volume
0  1.325412e+09  4.58  4.58  4.58   4.58     0.0
1  1.325412e+09  4.58  4.58  4.58   4.58     0.0
2  1.325412e+09  4.58  4.58  4.58   4.58     0.0

Últimas 3 filas:

            Timestamp     Open     High      Low    Close    Volume
7467520  1.773533e+09  71201.0  71202.0  71125.0  71125.0  1.149674
7467521  1.773533e+09  71121.0  71122.0  71116.0  71116.0  1.299773
7467522  1.773533e+09  71117.0  71125.0  71117.0  71118.0  1.561211

Resumen df.info():
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7467523 entries, 0 to 7467522
Data columns (total 6 columns):
 #   Column     Dtype
---  ------     -----
 0   Timestamp  float64
 1   Open       float64
 2   High       float64
 3   Low        float64
 4   Close      float64
 5   Volume     float64
dtypes: float64(6)
memory usage: 341.8 MB

Columna temporal detectada:
   Timestamp

Orden temporal detectado: CRONOLÓGICO o no claramente inverso (se confirmará tras la conversión a datetime).

### 0.3. Limpieza temporal y estandarización de columnas OHLCV

En esta sección se normaliza la dimensión temporal del dataset: se convierte la columna temporal detectada a tipo `datetime`, se renombra a un nombre estándar (`datetime`), se establece como índice y se ordena cronológicamente. Además, se estandarizan los nombres de las columnas OHLCV a formato `open`, `high`, `low`, `close`, `volume`.

In [17]:
# Limpieza temporal y estandarización de columnas OHLCV

if 'df_raw' not in globals():
    raise RuntimeError("df_raw no está definido. Ejecute primero las celdas de descarga y carga del CSV.")

# Copiamos el DataFrame bruto para trabajar sobre una versión intermedia
df = df_raw.copy()

# ----------------------------------------------------------------------
# Conversión de la columna temporal a datetime y renombrado estándar
# ----------------------------------------------------------------------

time_series = df[time_column_name]

# Detectamos si la columna temporal es numérica (posible Unix timestamp)
if pd.api.types.is_numeric_dtype(time_series):
    # Asumimos Unix timestamp en segundos, según la especificación del enunciado
    df['datetime'] = pd.to_datetime(time_series, unit='s', errors='coerce')
else:
    # Asumimos strings o tipos ya convertibles a datetime
    df['datetime'] = pd.to_datetime(time_series, errors='coerce', infer_datetime_format=True)

# Comprobamos si hay conversiones fallidas
n_invalid_dt = df['datetime'].isna().sum()
if n_invalid_dt > 0:
    print(f"Advertencia: {n_invalid_dt} filas tienen fecha/hora no convertible y se eliminarán.")
    df = df.dropna(subset=['datetime'])

# Establecemos 'datetime' como índice
df = df.drop(columns=[time_column_name])  # Eliminamos la columna original

# Orden cronológico ascendente
df = df.set_index('datetime').sort_index()

print("Índice temporal estandarizado a 'datetime' y ordenado cronológicamente.")

# ----------------------------------------------------------------------
# Estandarización de nombres de columnas OHLCV
# ----------------------------------------------------------------------

# Mapeo genérico de patrones a nombres estándar
ohlcv_targets = {
    'open': ['open'],
    'high': ['high', 'high_price'],
    'low':  ['low', 'low_price'],
    'close': ['close', 'close_price', 'price'],
    'volume': ['volume', 'volume_(btc)', 'volume_(currency)', 'vol']
}

col_mapping = {}
remaining_cols = list(df.columns)

for target_name, patterns in ohlcv_targets.items():
    found_col = None
    for col in remaining_cols:
        col_lower = col.lower()
        for pattern in patterns:
            if pattern in col_lower:
                found_col = col
                break
        if found_col is not None:
            break
    if found_col is not None:
        col_mapping[found_col] = target_name
        remaining_cols.remove(found_col)

# Renombramos las columnas encontradas
if col_mapping:
    df = df.rename(columns=col_mapping)

print("\nMapa de renombrado aplicado a columnas OHLCV:")
for orig, new in col_mapping.items():
    print(f"  {orig} -> {new}")

# ----------------------------------------------------------------------
# Eliminación de columnas no OHLCV
# ----------------------------------------------------------------------

cols_ohlcv = ['open', 'high', 'low', 'close', 'volume']

cols_present = [c for c in cols_ohlcv if c in df.columns]
if len(cols_present) < len(cols_ohlcv):
    missing = [c for c in cols_ohlcv if c not in df.columns]
    print("\nAdvertencia: faltan algunas columnas OHLCV esperadas:", missing)

# Seleccionamos solo las columnas OHLCV disponibles
cols_to_keep = cols_present

# Comentario: nos quedamos únicamente con OHLCV porque el objetivo de esta fase
# es trabajar con precios y volúmenes básicos; columnas auxiliares como
# 'Volume_(Currency)' o 'Weighted_Price' se descartan para simplificar el
# preprocesado y evitar duplicar información altamente correlacionada.

df = df[cols_to_keep]

print("\nColumnas finales tras la estandarización OHLCV:")
print(list(df.columns))

# Mostramos un pequeño resumen para verificar el resultado
print("\nResumen tras la limpieza temporal y estandarización OHLCV:")
print("  shape =", df.shape)
print("  Índice (datetime) desde", df.index.min(), "hasta", df.index.max())

Índice temporal estandarizado a 'datetime' y ordenado cronológicamente.

Mapa de renombrado aplicado a columnas OHLCV:
  Open -> open
  High -> high
  Low -> low
  Close -> close
  Volume -> volume

Columnas finales tras la estandarización OHLCV:
['open', 'high', 'low', 'close', 'volume']

Resumen tras la limpieza temporal y estandarización OHLCV:
  shape = (7467523, 5)
  Índice (datetime) desde 2012-01-01 10:01:00 hasta 2026-03-15 00:03:00

### 0.4. Filtrado temporal parametrizable con DATE_START y DATE_END

En esta sección se aplica el filtrado temporal sobre el índice `datetime` utilizando los parámetros globales `DATE_START` y `DATE_END`. El objetivo es trabajar únicamente con una ventana de datos coherente y controlada (por ejemplo, un mes de datos de 1 minuto).

In [18]:
# Filtrado temporal usando DATE_START y DATE_END

if 'df' not in globals():
    raise RuntimeError("df no está definido. Ejecute antes la celda de limpieza temporal (sección 3).")

# Convertimos las fechas de los parámetros globales a datetime
start_dt = pd.to_datetime(DATE_START)
end_dt = pd.to_datetime(DATE_END)

# Aplicamos el filtrado sobre el índice datetime
mask = (df.index >= start_dt) & (df.index <= end_dt)
df_window = df.loc[mask].copy()

if df_window.empty:
    raise ValueError(
        f"El filtrado temporal con DATE_START={DATE_START} y DATE_END={DATE_END} "
        "ha producido un DataFrame vacío. Revise el rango de fechas."
    )

n_rows = len(df_window)
print("Número de registros tras el filtrado temporal:", n_rows)
print("Rango real de fechas en la ventana filtrada:")
print("  Fecha mínima:", df_window.index.min())
print("  Fecha máxima:", df_window.index.max())

Número de registros tras el filtrado temporal: 38881
Rango real de fechas en la ventana filtrada:
  Fecha mínima: 2026-02-01 00:00:00
  Fecha máxima: 2026-02-28 00:00:00

### 0.5. Revisión de calidad del DataFrame filtrado

En esta sección se revisa la calidad del `DataFrame` ya filtrado temporalmente: se contabilizan valores ausentes, se aplican imputaciones controladas (forward fill limitado) sobre las columnas OHLCV cuando sea necesario y se detectan posibles duplicados en el índice temporal.

El objetivo es dejar constancia de los problemas de calidad encontrados y de las decisiones de limpieza tomadas.

In [19]:
# Revisión de calidad: NaNs, imputación controlada y duplicados

if 'df_window' not in globals():
    raise RuntimeError("df_window no está definido. Ejecute antes la celda de filtrado temporal (sección 4).")

# Trabajamos sobre una copia para la limpieza de calidad
df_clean = df_window.copy()

print("Valores ausentes por columna (antes de la imputación):")
na_before = df_clean.isna().sum()
print(na_before)

# Imputación forward fill limitada en columnas OHLCV si existen NaNs
cols_ohlcv = [c for c in ['open', 'high', 'low', 'close', 'volume'] if c in df_clean.columns]

if cols_ohlcv:
    # Contamos NaNs antes de imputar solo en OHLCV
    na_before_ohlcv = df_clean[cols_ohlcv].isna().sum().sum()

    if na_before_ohlcv > 0:
        print(f"\nAplicando forward fill (ffill) con límite de 5 periodos en columnas OHLCV (NaNs iniciales: {na_before_ohlcv}).")
        df_clean[cols_ohlcv] = df_clean[cols_ohlcv].ffill(limit=5)

        na_after_ohlcv = df_clean[cols_ohlcv].isna().sum().sum()
        imputed = na_before_ohlcv - na_after_ohlcv
        print(f"NaNs imputados en OHLCV: {imputed}")
        print(f"NaNs restantes en OHLCV tras imputación: {na_after_ohlcv}")
    else:
        print("\nNo se detectaron NaNs en columnas OHLCV. No se aplica imputación.")
else:
    print("\nAdvertencia: no se encontraron columnas OHLCV estándar para imputar (open, high, low, close, volume).")

# Recuento de NaNs final (todas las columnas)
print("\nValores ausentes por columna (después de la imputación):")
na_after = df_clean.isna().sum()
print(na_after)

# Detección de duplicados en el índice temporal
n_duplicated = df_clean.index.duplicated().sum()

if n_duplicated > 0:
    print(f"\nAdvertencia: se detectaron {n_duplicated} índices datetime duplicados.")
    # Podríamos decidir cómo resolverlos; por ahora solo se informa.
else:
    print("\nNo se detectaron índices datetime duplicados.")

print("\nResumen final de calidad tras esta sección:")
print("  shape =", df_clean.shape)
print("  Rango de fechas =", df_clean.index.min(), "→", df_clean.index.max())
print("  NaNs totales restantes =", int(df_clean.isna().sum().sum()))

Valores ausentes por columna (antes de la imputación):
open      0
high      0
low       0
close     0
volume    0
dtype: int64

No se detectaron NaNs en columnas OHLCV. No se aplica imputación.

Valores ausentes por columna (después de la imputación):
open      0
high      0
low       0
close     0
volume    0
dtype: int64

No se detectaron índices datetime duplicados.

Resumen final de calidad tras esta sección:
  shape = (38881, 5)
  Rango de fechas = 2026-02-01 00:00:00 → 2026-02-28 00:00:00
  NaNs totales restantes = 0

### 0.6. DataFrame final listo para la siguiente fase
En esta sección se muestra un resumen final del `DataFrame` limpio y filtrado que se utilizará como punto de partida para la construcción de barras alternativas en fases posteriores. Se imprimen las primeras filas y la estructura de tipos para verificar que la información relevante (OHLCV e índice temporal) está en el formato esperado.

Cerrar esta fase con una confirmación explícita del estado del `DataFrame` ayuda a documentar que los datos están listos para ser transformados sin necesidad de rehacer el preprocesado previo.

In [21]:
# Resumen final del DataFrame limpio y filtrado

if 'df_clean' not in globals():
    raise RuntimeError("df_clean no está definido. Asegúrese de haber ejecutado las celdas anteriores.")

print("DataFrame final (df_clean): primeras 5 filas:")
display(df_clean.head())

print("\nEstructura de df_clean (info):")
df_clean.info()

print("\nConfirmación:")
print("El DataFrame df_clean está limpio, filtrado en el rango temporal especificado y listo para la construcción de barras alternativas en la siguiente fase del pipeline.")

DataFrame final (df_clean): primeras 5 filas:

                        open     high      low    close     volume
datetime
2026-02-01 00:00:00  78644.0  78669.0  78591.0  78591.0   4.752846
2026-02-01 00:01:00  78591.0  78591.0  78556.0  78572.0  10.587024
2026-02-01 00:02:00  78571.0  78721.0  78571.0  78721.0   3.881749
2026-02-01 00:03:00  78721.0  78799.0  78707.0  78786.0   6.234550
2026-02-01 00:04:00  78778.0  78830.0  78757.0  78816.0   1.310776

Estructura de df_clean (info):
<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 38881 entries, 2026-02-01 00:00:00 to 2026-02-28 00:00:00
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   open    38881 non-null  float64
 1   high    38881 non-null  float64
 2   low     38881 non-null  float64
 3   close   38881 non-null  float64
 4   volume  38881 non-null  float64
dtypes: float64(5)
memory usage: 1.8 MB

Confirmación:
El DataFrame df_clean está limpio, filtrado en el rango temporal especificado y listo para la construcción de barras alternativas en la siguiente fase del pipeline.

## 1. Construcción y comparación de barras alternativas

**Propósito**: Transformar la serie de 1 minuto en representaciones alternativas (tick bars, volume bars y dollar bars) y justificar la elección de dollar bars como base para el resto del pipeline.

### 1.1 Motivación de las barras alternativas
- **Contenido esperado**:
  - Explicación breve de por qué las barras equidistantes en tiempo pueden ser subóptimas en mercados con actividad variable.
  - Introducción a la idea de homogeneizar la información de cada barra según número de transacciones, volumen o valor nocional.
- **Indicaciones para el código**:
  - No se implementa aún; solo se describe el objetivo de las transformaciones.

### 1.2 Definición conceptual de tick bars
- **Contenido esperado**:
  - Definición de tick bars: agrupar un número fijo de transacciones (ticks) por barra.
  - Aclarar que, al trabajar con datos agregados por minuto, se está aproximando este concepto y debe dejarse documentada la limitación.
- **Indicaciones para el código**:
  - Diseño de una lógica que acumule "ticks" equivalentes hasta alcanzar un umbral dado y luego cierre la barra.

### 1.3 Definición conceptual de volume bars
- **Contenido esperado**:
  - Definición de volume bars: agrupar observaciones hasta acumular un volumen negociado fijo.
  - Ventajas esperadas: cada barra contiene un nivel de actividad relativamente comparable.
- **Indicaciones para el código**:
  - Lógica de acumulación de volumen hasta umbral y cierre de barra, asignando un timestamp representativo (por ejemplo, el del último minuto incluido en la barra).

### 1.4 Definición conceptual de dollar bars
- **Contenido esperado**:
  - Definición de dollar bars: agrupar observaciones hasta acumular un valor nocional (precio × volumen) fijo.
  - Motivación: capturar mejor el flujo de capital que atraviesa el mercado.
- **Indicaciones para el código**:
  - Lógica similar a volume bars, pero acumulando precio × volumen en lugar de volumen.

### 1.5 Construcción práctica de tick, volume y dollar bars
- **Contenido esperado**:
  - Descripción de cómo se construyen, a partir del dataframe de 1 minuto, tres nuevas series de barras: tick, volumen y dólar.
  - Documentar claramente los umbrales utilizados para cada tipo (por ejemplo, volumen medio, nocional medio, etc.).
- **Gráficas recomendadas**:
  - **Serie temporal del precio de cierre** para cada tipo de barra (tres subplots con la misma escala de fechas) para comparar la granularidad.

### 1.6 Comparación descriptiva entre las tres representaciones
- **Contenido esperado**:
  - Número de barras resultantes de cada método en la misma ventana temporal.
  - Estadísticos básicos de retornos por barra para cada tipo.
- **Gráficas recomendadas**:
  - **Histogramas o KDE de retornos** por tipo de barra usando `seaborn`.
  - **Boxplots de retornos** por tipo de barra para visualizar diferencias de dispersión y colas.

### 1.7 Justificación de la selección de dollar bars
- **Contenido esperado**:
  - Discusión apoyada en métricas y gráficos sobre cuál representación captura mejor la dinámica del activo.
  - Justificación explícita de por qué se seleccionan las dollar bars para el resto del notebook (por ejemplo, mayor estabilidad en distribución de retornos, mejor adaptación a cambios de régimen de volumen).

### Markdown introductorio de la sección 1 (guía de redacción)

En esta sección se explicará que:
- Las barras temporales de longitud fija pueden distorsionar la información en periodos de alta o baja actividad.
- Las barras alternativas (tick, volumen y dólar) intentan que cada barra contenga una cantidad de información comparable.
- Siguiendo la literatura cuantitativa, las dollar bars son una candidata natural para trabajar con flujos de capital.
- Al final, se selecciona un tipo de barra (dollar bars) para las siguientes secciones del pipeline.

**Output clave de la sección 1**:
- DataFrame de barras de tipo dólar (dollar bars) con columnas de precios, volúmenes y timestamps representativos.
- Justificación documentada de por qué se escogen las dollar bars como base para la Sección 2.

**Riesgos a comentar en el texto**:
- No documentar los umbrales utilizados para construir las barras, dificultando la reproducibilidad.
- No aclarar cómo se asigna el timestamp a cada barra.
- Comparar distribuciones de retornos sin ajustar escalas ni ventanas de observación.
- Ignorar el sesgo que introduce aproximar tick bars a partir de datos ya agregados por minuto.

## 2. Diferenciación fraccional de la serie de precios

**Propósito**: Aplicar diferenciación fraccional a la serie de precios (sobre dollar bars) para obtener una serie más estacionaria sin perder completamente la memoria de largo plazo.

### 2.1 Motivación de la diferenciación fraccional
- **Contenido esperado**:
  - Descripción del problema de no estacionariedad en series financieras.
  - Limitaciones de la diferenciación entera (d = 1), que elimina demasiada memoria.
  - Idea general de la diferenciación fraccional como compromiso entre memoria y estacionariedad.

### 2.2 Configuración de valores de d a comparar
- **Contenido esperado**:
  - Definir explícitamente el conjunto de valores de d: 0.0, 0.3, 0.5, 0.8, 1.0.
  - Explicar por qué se elige este rango (desde sin diferenciación hasta diferenciación entera).
- **Indicaciones para el código**:
  - Aquí se definirá una lista de valores de d y una rutina genérica para aplicar la diferenciación fraccional a la serie de precios.

### 2.3 Cálculo conceptual de las series diferenciadas fraccionalmente
- **Contenido esperado**:
  - Explicación breve de la idea de pesos decrecientes y convolución con la serie de precios.
  - Comentario sobre la pérdida de observaciones al inicio debido a la ventana efectiva.
- **Gráficas recomendadas**:
  - **Subplots de series temporales** mostrando la serie original y varias versiones diferenciadas para diferentes valores de d, centradas en la misma ventana temporal.

### 2.4 Evaluación de memoria vs estacionariedad
- **Contenido esperado**:
  - Cálculo de medidas descriptivas de dependencia temporal (por ejemplo, autocorrelación) para cada valor de d.
  - Uso de algún criterio práctico para juzgar el grado de estacionariedad (p. ej., rapidez de decaimiento de la ACF).
- **Gráficas recomendadas**:
  - **Gráficas de ACF/PACF** para varios valores de d.
  - **Histogramas o KDE** de las series diferenciadas para ver cambios en varianza y forma de la distribución.
  - Opcional: **gráfica de varianza vs d**.

### 2.5 Selección de un valor de d para el pipeline
- **Contenido esperado**:
  - Discusión de los resultados: cómo cambia la memoria residual y la varianza al variar d.
  - Elección de un valor de d que ofrezca equilibrio razonable (justificación argumentada).
- **Decisión**:
  - Fijar un valor de d y documentar por qué (por ejemplo, se puede justificar un valor intermedio).

### Markdown introductorio de la sección 2 (guía de redacción)

En esta sección se explicará que:
- Existe una tensión entre cumplir supuestos de estacionariedad y preservar la información económica de largo plazo.
- La diferenciación fraccional permite modular esa tensión con un parámetro continuo d.
- Se exploran varios valores de d y se elige uno de manera explícita, apoyándose en métricas visuales y descriptivas.

**Output clave de la sección 2**:
- Columna en el dataframe de dollar bars correspondiente a la serie diferenciada fraccionalmente con el valor de d seleccionado.
- Decisión documentada sobre d, que se utilizará en la construcción de features y en la matriz de covarianza de la Sección 3.

**Riesgos a comentar en el texto**:
- No tratar explícitamente la pérdida de observaciones al inicio, provocando desalineaciones con otras variables.
- Comparar ACF de series de longitudes muy diferentes sin anotarlo.
- Interpretar pruebas de estacionariedad de forma excesivamente binaria.
- No comentar el cambio de escala (varianza) que introduce la diferenciación.

## 3. Construcción y limpieza de la matriz de covarianza

**Propósito**: Construir un conjunto de features internas a partir de BTC/USDT (sobre dollar bars y serie diferenciada) y estimar la matriz de covarianza empírica, para posteriormente limpiarla mediante eigenvalue clipping y reducir el impacto del ruido.

### 3.1 Construcción de features internas
- **Contenido esperado**:
  - Definición y cálculo de:
    - Retornos (por ejemplo, sobre la serie de precios logarítmicos o diferenciada).
    - Volatilidad rolling (desviación estándar en una ventana fija).
    - Media rolling (promedio de precios o retornos en ventana).
    - Cambios relativos en volumen (volume change).
  - Alineación de todas las series y gestión de NaNs iniciales por ventanas rolling.
- **Indicaciones para el código**:
  - Aquí se definen y añaden columnas al dataframe con cada feature interna.

### 3.2 Construcción de la matriz de covarianza empírica
- **Contenido esperado**:
  - Selección de una subventana coherente sobre la que estimar la covarianza (últimas N barras, por ejemplo).
  - Cálculo de la matriz de covarianza muestral entre todas las features.
- **Gráficas recomendadas**:
  - **Heatmap de la matriz de covarianza** (seaborn) para visualizar patrones de correlación.

### 3.3 Análisis del espectro de eigenvalores
- **Contenido esperado**:
  - Descomposición en eigenvalores y eigenvectores de la matriz de covarianza.
  - Discusión sobre la presencia de muchos eigenvalores pequeños asociados a ruido.
- **Gráficas recomendadas**:
  - **Histograma o gráfico de barras de eigenvalores** antes de la limpieza.

### 3.4 Limpieza por eigenvalue clipping
- **Contenido esperado**:
  - Definición de un umbral simple para eigenvalores (por ejemplo, percentil o mínimo permitido).
  - Reemplazo de eigenvalores por el umbral cuando estén por debajo y reconstrucción de la matriz de covarianza limpia.
- **Gráficas recomendadas**:
  - **Histograma o barras de eigenvalores tras el clipping**.
  - Opcional: **scatter eigenvalores originales vs limpiados**.

### 3.5 Comparación antes / después de la limpieza
- **Contenido esperado**:
  - Comparación visual entre la matriz de covarianza original y la limpia.
  - Alguna métrica global de diferencia (por ejemplo, norma de la diferencia) comentada a nivel cualitativo.
- **Gráficas recomendadas**:
  - **Heatmap de la matriz de covarianza limpia** (seaborn).
  - Comparación lado a lado (dos heatmaps) o en dos figuras consecutivas.

### Markdown introductorio de la sección 3 (guía de redacción)

En esta sección se explicará que:
- Incluso con un solo activo, las features internas pueden ser altamente correlacionadas y estar fuertemente afectadas por ruido muestral.
- La matriz de covarianza empírica en alta dimensión (o con pocas observaciones) es inestable.
- El clipping de eigenvalores es una técnica sencilla pero útil para reducir el impacto del ruido, aunque no sea la más sofisticada disponible.

**Output clave de la sección 3**:
- Conjunto de features internas alineadas y sin NaNs, listo para usarse en el etiquetado.
- Matriz de covarianza limpia asociada a dicho conjunto de features, útil como referencia para interpretación de riesgos y relaciones entre variables.

**Riesgos a comentar en el texto**:
- No alinear correctamente las ventanas rolling, generando covarianzas sobre datos desfasados.
- Elegir un umbral de clipping arbitrario sin justificarlo mínimamente.
- Interpretar la matriz limpia como “verdadera” sin matices.
- Ignorar las diferencias de escala entre features (no estandarizar ni comentarlo).

## 4. Etiquetado de eventos mediante el método de triple barrera

**Propósito**: Asignar etiquetas de dirección (por ejemplo, +1, 0, −1) a eventos sobre la serie de dollar bars utilizando el método de triple barrera con distintos esquemas de thresholds (fijos y dinámicos), para obtener un conjunto de datos etiquetado apto para modelos de ML.

### 4.1 Motivación del etiquetado con triple barrera
- **Contenido esperado**:
  - Problema de definir “éxito” o “fracaso” de una operación usando solo un horizonte temporal fijo.
  - Introducción al método de triple barrera: combinar barrera superior, inferior y temporal.
- **Indicaciones para el código**:
  - Descripción de cómo se identificarán los eventos de entrada (por ejemplo, cada barra o un subconjunto).

### 4.2 Definición conceptual de las tres barreras
- **Contenido esperado**:
  - Barrera superior (take profit) como cierto porcentaje o múltiplo de volatilidad por encima del precio de entrada.
  - Barrera inferior (stop loss) simétricamente por debajo.
  - Barrera temporal (máxima duración del evento en número de barras).
- **Gráficas recomendadas**:
  - **Ejemplos ilustrativos** sobre un pequeño tramo de la serie con las tres barreras dibujadas.

### 4.3 Thresholds fijos: 1 % y 2 %
- **Contenido esperado**:
  - Definición de thresholds fijos (±1 % y ±2 %) en términos de cambio porcentual sobre el precio de entrada.
  - Criterio de etiquetado: qué barrera se toca primero determina la etiqueta (+1, −1, 0).
- **Gráficas recomendadas**:
  - **Ejemplos de eventos** con thresholds fijos, mostrando las trayectorias que alcanzan cada barrera.

### 4.4 Threshold dinámico basado en volatilidad rolling
- **Contenido esperado**:
  - Uso de una medida de volatilidad rolling para definir barreras proporcionales al riesgo local.
  - Explicación del factor multiplicador aplicado a la volatilidad para obtener la distancia de las barreras.
- **Gráficas recomendadas**:
  - **Ejemplos de eventos** donde las barreras cambian de amplitud según la volatilidad local.

### 4.5 Comparación de la distribución de etiquetas entre métodos
- **Contenido esperado**:
  - Cálculo de la proporción de etiquetas +1, 0, −1 para cada esquema: 1 %, 2 % y volatilidad rolling.
  - Discusión sobre el equilibrio de clases y su impacto potencial en el modelado.
- **Gráficas recomendadas**:
  - **Gráficos de barras** de distribución de etiquetas para cada método.
  - Opcional: **tabla o heatmap de contingencia** entre etiquetas de diferentes métodos.

### Markdown introductorio de la sección 4 (guía de redacción)

En esta sección se explicará que:
- El etiquetado es el puente entre la serie de precios y el problema de clasificación para el ML.
- El método de triple barrera permite incorporar simultáneamente magnitud del movimiento y límite temporal.
- Se comparan thresholds fijos y un umbral dinámico basado en volatilidad, motivando por qué la volatilidad es un buen proxy de riesgo local.

**Output clave de la sección 4**:
- Columnas de etiquetas correspondientes a cada esquema de thresholds (1 %, 2 %, volatilidad rolling) asociadas a las observaciones de dollar bars.
- Selección opcional de un esquema principal para utilizarlo como referencia en la validación cruzada temporal de la Sección 5, o decisión explícita de mantener varios para comparación.

**Riesgos a comentar en el texto**:
- No tratar correctamente la barrera temporal, dejando eventos de duración indefinida.
- No documentar cómo se gestionan eventos solapados.
- Ignorar el desequilibrio de clases que pueden producir ciertos thresholds.
- Desalinear los precios usados para las barreras respecto a las barras empleadas para los features.

## 5. Validación cruzada temporal y definición de splits

**Propósito**: Definir esquemas de validación cruzada temporal que respeten el orden cronológico de los datos (sin mezclar pasado y futuro), para distintos ratios de train/test (70/30, 80/20, 90/10), dejando preparados los índices que se usarán en el entrenamiento de modelos.

### 5.1 Problemas de la validación cruzada aleatoria en series temporales
- **Contenido esperado**:
  - Explicación de por qué el shuffle clásico rompe la causalidad.
  - Ejemplos conceptuales de fuga de información (leakage) cuando el futuro se utiliza indirectamente para predecir el pasado.

### 5.2 Definición de esquemas de splits temporales
- **Contenido esperado**:
  - Descripción de splits de un solo corte: primero tramo de entrenamiento, luego tramo de test.
  - Definición explícita de los tres casos: 70/30, 80/20 y 90/10 en términos de número de observaciones (o fechas).
- **Indicaciones para el código**:
  - Diseño de funciones sencillas que, dado el dataframe de barras etiquetadas, devuelvan índices de train y test para cada escenario.

### 5.3 Construcción de índices de train/test
- **Contenido esperado**:
  - Asociación de cada split con rangos de índices o de fechas.
  - Verificación de que features y etiquetas están alineadas en ambos conjuntos.
- **Visualizaciones sugeridas**:
  - Tabla resumen con número de observaciones y rango de fechas de train y test para cada split.

### 5.4 Visualización de los splits sobre la serie temporal
- **Contenido esperado**:
  - Representación visual sobre la serie de precios (o sobre el índice temporal) de qué parte se utiliza para train y cuál para test en cada ratio.
- **Gráficas recomendadas**:
  - **Line plot de la serie** con diferentes colores o sombreado para las zonas de train y test.
  - **Diagrama de bloques** en el eje temporal para comparar visualmente 70/30, 80/20 y 90/10.

### 5.5 Discusión de ventajas y limitaciones de cada esquema
- **Contenido esperado**:
  - Comentario sobre el compromiso entre:
    - Más datos de entrenamiento (mejor ajuste potencial).
    - Periodo de test suficientemente representativo y reciente.
  - Mención de posibles extensiones más sofisticadas (walk-forward, purged k-fold) aunque no se implementen aquí.

### Markdown introductorio de la sección 5 (guía de redacción)

En esta sección se explicará que:
- La evaluación de modelos en finanzas debe respetar el orden temporal para evitar fuga de información.
- Diferentes ratios de train/test reflejan distintas prioridades (aprendizaje vs evaluación).
- Aunque se usan esquemas sencillos de un solo corte, estos ya representan una mejora importante respecto a la validación cruzada aleatoria.

**Output clave de la sección 5**:
- Índices o rangos de fechas claramente definidos para train y test en los tres escenarios (70/30, 80/20, 90/10).
- Base preparada para entrenar modelos en otro notebook reutilizando estos splits sin rediseñarlos.

**Riesgos a comentar en el texto**:
- Reordenar las observaciones de forma aleatoria antes de dividir.
- No tener en cuenta que los regímenes de mercado pueden variar entre train y test.
- Permitir que alguna feature se calcule con información que invade el tramo de test sin comentarlo.

In [ ]:
# Carga del CSV seleccionado y exploración básica

# Leemos el archivo CSV seleccionado en la celda anterior
print("Leyendo CSV desde:")
print("  ", DATA_CSV_PATH)

df_raw = pd.read_csv(DATA_CSV_PATH)

print("\nDimensiones del DataFrame bruto:")
print("  shape =", df_raw.shape)

print("\nTipos de datos (dtypes):")
print(df_raw.dtypes)

print("\nPrimeras 3 filas:")
display(df_raw.head(3))

print("\nÚltimas 3 filas:")
display(df_raw.tail(3))

print("\nResumen df.info():")
df_raw.info()

# ----------------------------------------------------------------------
# Detección robusta de la columna temporal
# ----------------------------------------------------------------------

possible_time_names = [
    "timestamp", "date", "time", "datetime", "open time", "open_time"
]

# Buscamos coincidencias case-insensitive y permitimos espacios/guiones bajos
lower_cols = {col.lower(): col for col in df_raw.columns}

found_time_col = None
for candidate in possible_time_names:
    for col_lower, col_original in lower_cols.items():
        if candidate in col_lower:
            found_time_col = col_original
            break
    if found_time_col is not None:
        break

if found_time_col is None:
    raise ValueError(
        "No se pudo detectar una columna temporal. Revise los nombres de columna "
        "y actualice la lista de posibles variantes."
    )

print("\nColumna temporal detectada:")
print("  ", found_time_col)

# ----------------------------------------------------------------------
# Detección de si el orden temporal está invertido
# ----------------------------------------------------------------------

# Tomamos algunas muestras del principio y del final para intentar inferir el orden
sample_start = df_raw[found_time_col].head(5)
sample_end = df_raw[found_time_col].tail(5)

# Intentamos convertir estas muestras a datetime de forma flexible
sample_start_dt = pd.to_datetime(sample_start, errors="coerce", infer_datetime_format=True)
sample_end_dt = pd.to_datetime(sample_end, errors="coerce", infer_datetime_format=True)

is_reverse_order = False
if not sample_start_dt.isna().all() and not sample_end_dt.isna().all():
    first_ts = sample_start_dt.iloc[0]
    last_ts = sample_end_dt.iloc[-1]
    if pd.notna(first_ts) and pd.notna(last_ts):
        is_reverse_order = first_ts > last_ts

if is_reverse_order:
    print("\nOrden temporal detectado: INVERSO (últimas fechas primero). Se corregirá en la etapa de limpieza temporal.")
else:
    print("\nOrden temporal detectado: CRONOLÓGICO o no claramente inverso (se confirmará tras la conversión a datetime).")

# Guardamos el nombre de la columna temporal para usarlo en la siguiente fase
time_column_name = found_time_col

Leyendo CSV desde:
   C:\Users\Usuario\.cache\kagglehub\datasets\mczielinski\bitcoin-historical-data\versions\538\btcusd_1-min_data.csv

Dimensiones del DataFrame bruto:
  shape = (7467523, 6)

Tipos de datos (dtypes):
Timestamp    float64
Open         float64
High         float64
Low          float64
Close        float64
Volume       float64
dtype: object

Primeras 3 filas:

      Timestamp  Open  High   Low  Close  Volume
0  1.325412e+09  4.58  4.58  4.58   4.58     0.0
1  1.325412e+09  4.58  4.58  4.58   4.58     0.0
2  1.325412e+09  4.58  4.58  4.58   4.58     0.0

Últimas 3 filas:

            Timestamp     Open     High      Low    Close    Volume
7467520  1.773533e+09  71201.0  71202.0  71125.0  71125.0  1.149674
7467521  1.773533e+09  71121.0  71122.0  71116.0  71116.0  1.299773
7467522  1.773533e+09  71117.0  71125.0  71117.0  71118.0  1.561211

Resumen df.info():
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7467523 entries, 0 to 7467522
Data columns (total 6 columns):
 #   Column     Dtype
---  ------     -----
 0   Timestamp  float64
 1   Open       float64
 2   High       float64
 3   Low        float64
 4   Close      float64
 5   Volume     float64
dtypes: float64(6)
memory usage: 341.8 MB

Columna temporal detectada:
   Timestamp

Orden temporal detectado: CRONOLÓGICO o no claramente inverso (se confirmará tras la conversión a datetime).

C:\Users\Usuario\AppData\Local\Temp\ipykernel_7316\3030589010.py:62: UserWarning: The argument 'infer_datetime_format' is deprecated and will be removed in a future version. A strict version of it is now the default, see https://pandas.pydata.org/pdeps/0004-consistent-to-datetime-parsing.html. You can safely remove this argument.
  sample_start_dt = pd.to_datetime(sample_start, errors="coerce", infer_datetime_format=True)
C:\Users\Usuario\AppData\Local\Temp\ipykernel_7316\3030589010.py:63: UserWarning: The argument 'infer_datetime_format' is deprecated and will be removed in a future version. A strict version of it is now the default, see https://pandas.pydata.org/pdeps/0004-consistent-to-datetime-parsing.html. You can safely remove this argument.
  sample_end_dt = pd.to_datetime(sample_end, errors="coerce", infer_datetime_format=True)